#!/usr/bin/env bash
# Cuts a minor release of MDator.
#
#   1. Branches release/vX.Y.0 off origin/main (X.Y derived by minor-bumping
#      the latest vMAJOR.MINOR.PATCH tag).
#   2. Promotes the [Unreleased] section in CHANGELOG.md to a dated release
#      section, rewrites the trailing compare links, leaves a fresh empty
#      [Unreleased] above.
#   3. Opens a release PR, waits for CI, merges with a merge commit, deletes
#      the branch.
#   4. Pulls main, creates and pushes the annotated tag — the publish workflow
#      picks it up and pushes the package to nuget.org.
#
# Always a minor bump. Patch/major bumps are not supported by this script
# because MDator's release line is minor-only by convention.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

REPO_SLUG="ArtnimIO/MDator"

note() { printf '==> %s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- Pre-flight ---------------------------------------------------------------

command -v gh >/dev/null 2>&1 || fail "gh CLI not found on PATH"
gh auth status >/dev/null 2>&1 || fail "gh is not authenticated (run 'gh auth login')"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
[[ "${CURRENT_BRANCH}" == "main" ]] \
  || fail "must be on main (currently on '${CURRENT_BRANCH}')"

git diff-index --quiet HEAD -- \
  || fail "working tree has uncommitted changes to tracked files"

note "Fetching origin"
git fetch origin --tags --quiet

LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse '@{u}')
[[ "${LOCAL}" == "${REMOTE}" ]] \
  || fail "main is not in sync with origin/main (pull or push first)"

# Latest vMAJOR.MINOR.PATCH tag (ignores -rc / suffixed tags).
LATEST_TAG=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname \
  | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
  | head -n1 || true)
[[ -n "${LATEST_TAG}" ]] || fail "no vMAJOR.MINOR.PATCH tag found"

[[ "${LATEST_TAG}" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] \
  || fail "latest tag '${LATEST_TAG}' does not parse as vMAJOR.MINOR.PATCH"
PREV_MAJOR="${BASH_REMATCH[1]}"
PREV_MINOR="${BASH_REMATCH[2]}"

NEW_MINOR=$((PREV_MINOR + 1))
NEW_VERSION="${PREV_MAJOR}.${NEW_MINOR}.0"
NEW_TAG="v${NEW_VERSION}"
RELEASE_BRANCH="release/${NEW_TAG}"
TODAY=$(date +%Y-%m-%d)

! git rev-parse -q --verify "refs/tags/${NEW_TAG}" >/dev/null \
  || fail "tag ${NEW_TAG} already exists"
! git rev-parse -q --verify "refs/heads/${RELEASE_BRANCH}" >/dev/null \
  || fail "branch ${RELEASE_BRANCH} already exists locally"

[[ -f CHANGELOG.md ]] || fail "CHANGELOG.md not found"
grep -q '^## \[Unreleased\]' CHANGELOG.md \
  || fail "CHANGELOG.md does not have an '## [Unreleased]' section"
grep -q '^\[Unreleased\]:' CHANGELOG.md \
  || fail "CHANGELOG.md does not have an '[Unreleased]:' link reference"

note "Latest tag    : ${LATEST_TAG}"
note "New release   : ${NEW_TAG} (${TODAY})"
note "Release branch: ${RELEASE_BRANCH}"

# --- Branch + CHANGELOG -------------------------------------------------------

git checkout -b "${RELEASE_BRANCH}"

# Promote [Unreleased] heading: keep an empty [Unreleased] on top, insert a new
# dated [NEW_VERSION] section that owns the entries that were under Unreleased.
awk -v new_version="${NEW_VERSION}" -v today="${TODAY}" '
    !replaced && /^## \[Unreleased\]/ {
        print "## [Unreleased]"
        print ""
        print "## [" new_version "] - " today
        replaced = 1
        next
    }
    { print }
' CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md

# Rewrite link refs:
#   [Unreleased]: ...compare/<PREV>...HEAD  →  ...compare/<NEW_TAG>...HEAD
# and insert immediately after:
#   [NEW_VERSION]: ...compare/<PREV>...<NEW_TAG>
awk \
    -v new_version="${NEW_VERSION}" \
    -v new_tag="${NEW_TAG}" \
    -v prev_tag="${LATEST_TAG}" \
    -v repo="${REPO_SLUG}" '
    /^\[Unreleased\]:/ {
        print "[Unreleased]: https://github.com/" repo "/compare/" new_tag "...HEAD"
        print "[" new_version "]: https://github.com/" repo "/compare/" prev_tag "..." new_tag
        next
    }
    { print }
' CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md

git add CHANGELOG.md
git commit -m "Release ${NEW_TAG}"
git push -u origin "${RELEASE_BRANCH}"

# --- PR + merge ---------------------------------------------------------------

note "Opening release PR"
PR_BODY=$(cat <<EOF
Cuts ${NEW_TAG} by promoting the Unreleased section of CHANGELOG.md to a dated release entry and rewriting the trailing compare links.

Merging this PR is followed by tagging ${NEW_TAG} on main; the publish workflow then packages and pushes to nuget.org.

Generated by create-release.sh.
EOF
)
gh pr create \
    --base main \
    --head "${RELEASE_BRANCH}" \
    --title "Release ${NEW_TAG}" \
    --body "${PR_BODY}"

note "Waiting for required checks on ${RELEASE_BRANCH}"
# `gh pr checks --watch` only watches checks that already exist; right after
# `gh pr create` GitHub usually hasn't registered the workflow runs against
# the head ref yet, and --watch exits early with "no checks reported". Poll
# the JSON output until at least one check shows up, then hand off to --watch.
poll_attempts=0
until [[ "$(gh pr checks "${RELEASE_BRANCH}" --json state --jq 'length' 2>/dev/null || echo 0)" -gt 0 ]]; do
    poll_attempts=$((poll_attempts + 1))
    if (( poll_attempts > 24 )); then
        fail "no checks reported on ${RELEASE_BRANCH} after 2 minutes"
    fi
    sleep 5
done
gh pr checks "${RELEASE_BRANCH}" --watch --interval 15

note "Merging release PR"
gh pr merge "${RELEASE_BRANCH}" --merge --delete-branch

# --- Tag main -----------------------------------------------------------------

note "Syncing local main"
git checkout main
git pull --ff-only origin main

note "Tagging ${NEW_TAG}"
git tag -a "${NEW_TAG}" -m "Release ${NEW_TAG}"
git push origin "${NEW_TAG}"

note "Done. Publish workflow on tag ${NEW_TAG} will push to nuget.org."
