using System.Collections.Generic;
using System.Linq;

namespace MDator.SourceGenerator;

/// <summary>
/// Emits the whole generated MDator surface for a consuming assembly:
/// <list type="bullet">
///   <item>The <c>MDatorGeneratedRegistration</c> static class with a
///     <c>[ModuleInitializer]</c> that registers every handler with DI.</item>
///   <item>The <c>GeneratedMediator</c> sealed implementation of
///     <see cref="IMediator"/> with compile-time dispatch for every request,
///     stream and notification the generator discovered.</item>
/// </list>
/// </summary>
internal static class MediatorEmitter
{
    /// <summary>
    /// Returns handlers sorted so that derived message types come before their
    /// base types. This prevents CS8120 (unreachable switch case) when a request
    /// type inherits from another request type.
    /// </summary>
    private static List<HandlerInfo> SortedByTypeHierarchy(IEnumerable<HandlerInfo> handlers) =>
        handlers.OrderByDescending(h => h.MessageTypeDepth).ToList();

    public static string Emit(PipelineModel model)
    {
        // Group handlers by kind for easier lookup.
        var requestHandlers = model.Handlers
            .Where(h => h.Kind == HandlerKind.RequestWithResponse && !h.HandlerIsOpenGeneric)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.First());

        var voidHandlers = model.Handlers
            .Where(h => h.Kind == HandlerKind.RequestVoid && !h.HandlerIsOpenGeneric)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.First());

        var streamHandlers = model.Handlers
            .Where(h => h.Kind == HandlerKind.Stream && !h.HandlerIsOpenGeneric)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.First());

        var notificationHandlers = model.Handlers
            .Where(h => h.Kind == HandlerKind.Notification && !h.HandlerIsOpenGeneric)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.ToList());

        var preProcessors = model.Handlers
            .Where(h => h.Kind == HandlerKind.PreProcessor)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.ToList());

        var postProcessors = model.Handlers
            .Where(h => h.Kind == HandlerKind.PostProcessor)
            .GroupBy(h => (h.MessageType.GlobalName, h.ResponseType!.GlobalName))
            .ToDictionary(g => g.Key, g => g.ToList());

        var exceptionHandlers = model.Handlers
            .Where(h => h.Kind == HandlerKind.ExceptionHandler)
            .GroupBy(h => (h.MessageType.GlobalName, h.ResponseType!.GlobalName))
            .ToDictionary(g => g.Key, g => g.OrderByDescending(h => h.ExceptionDepth).ToList());

        var exceptionActions = model.Handlers
            .Where(h => h.Kind == HandlerKind.ExceptionAction)
            .GroupBy(h => h.MessageType.GlobalName)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(h => h.ExceptionDepth).ToList());

        // Open behaviors, sorted by declared order. Closed-at-compile-time
        // pipeline behaviors (not open generic) are handled as runtime-resolved
        // services via the enumeration fallback — fusing them explicitly would
        // require key-by-(Req,Resp) which adds little value over MSDI's enumerator.
        var openRequestBehaviors = model.Behaviors
            .Where(b => b.Kind == BehaviorKind.Request && b.IsOpenGeneric)
            .OrderBy(b => b.Order).ThenBy(b => b.BehaviorType.GlobalName)
            .ToList();

        var openStreamBehaviors = model.Behaviors
            .Where(b => b.Kind == BehaviorKind.Stream && b.IsOpenGeneric)
            .OrderBy(b => b.Order).ThenBy(b => b.BehaviorType.GlobalName)
            .ToList();

        var w = new CodeWriter();
        EmitHeader(w);
        EmitNamespaceOpen(w, model.RootNamespace);

        EmitRegistration(w, model, requestHandlers, voidHandlers, streamHandlers,
            notificationHandlers, preProcessors, postProcessors,
            exceptionHandlers, exceptionActions);

        w.Line();

        EmitMediator(w, requestHandlers, voidHandlers, streamHandlers,
            notificationHandlers, preProcessors, postProcessors,
            exceptionHandlers, exceptionActions,
            openRequestBehaviors, openStreamBehaviors);

        EmitNamespaceClose(w);
        return w.ToString();
    }

    private static void EmitHeader(CodeWriter w)
    {
        w.Line("// <auto-generated />");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591 // missing XML doc on generated members");
        w.Line();
        w.Line("using System;");
        w.Line("using System.Collections.Generic;");
        w.Line("using System.Runtime.CompilerServices;");
        w.Line("using System.Threading;");
        w.Line("using System.Threading.Tasks;");
        w.Line("using Microsoft.Extensions.DependencyInjection;");
        w.Line("using MDator;");
        w.Line();
    }

    private static string NsIdentifier(string rootNamespace)
    {
        var sb = new System.Text.StringBuilder();
        foreach (var c in rootNamespace)
        {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.Length == 0 ? "GeneratedMDator" : sb.ToString();
    }

    private static void EmitNamespaceOpen(CodeWriter w, string rootNamespace)
    {
        w.Line($"namespace MDator.Generated.{NsIdentifier(rootNamespace)}");
        w.OpenBrace();
    }

    private static void EmitNamespaceClose(CodeWriter w) => w.CloseBrace();

    private static void EmitRegistration(
        CodeWriter w,
        PipelineModel model,
        Dictionary<string, HandlerInfo> requestHandlers,
        Dictionary<string, HandlerInfo> voidHandlers,
        Dictionary<string, HandlerInfo> streamHandlers,
        Dictionary<string, List<HandlerInfo>> notificationHandlers,
        Dictionary<string, List<HandlerInfo>> preProcessors,
        Dictionary<(string, string), List<HandlerInfo>> postProcessors,
        Dictionary<(string, string), List<HandlerInfo>> exceptionHandlers,
        Dictionary<string, List<HandlerInfo>> exceptionActions)
    {
        w.Line("internal static class MDatorGeneratedRegistration");
        w.OpenBrace();
        w.Line("[ModuleInitializer]");
        w.Line("internal static void Init()");
        w.OpenBrace();
        w.Line("global::MDator.MDatorGeneratedHook.Registrations.Add(Register);");
        w.CloseBrace();
        w.Line();

        w.Line("private static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::MDator.MDatorConfiguration cfg)");
        w.OpenBrace();
        w.Line("var lt = cfg.Lifetime;");
        w.Line("// IMediator registered once per consuming assembly set; TryAdd to avoid duplicates when");
        w.Line("// multiple generated registrations run in the same composition root.");
        w.Line("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IMediator), typeof(GeneratedMediator), lt));");
        w.Line("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.ISender), static sp => sp.GetRequiredService<global::MDator.IMediator>(), lt));");
        w.Line("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IPublisher), static sp => sp.GetRequiredService<global::MDator.IMediator>(), lt));");
        w.Line();

        // Request handlers with response
        foreach (var h in requestHandlers.Select(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({h.HandlerType.GlobalName}), typeof({h.HandlerType.GlobalName}), lt));");
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestHandler<{h.MessageType.GlobalName}, {h.ResponseType!.GlobalName}>), static sp => sp.GetRequiredService<{h.HandlerType.GlobalName}>(), lt));");
        }
        // Void handlers
        foreach (var h in voidHandlers.Select(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({h.HandlerType.GlobalName}), typeof({h.HandlerType.GlobalName}), lt));");
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestHandler<{h.MessageType.GlobalName}>), static sp => sp.GetRequiredService<{h.HandlerType.GlobalName}>(), lt));");
        }
        // Stream handlers
        foreach (var h in streamHandlers.Select(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({h.HandlerType.GlobalName}), typeof({h.HandlerType.GlobalName}), lt));");
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IStreamRequestHandler<{h.MessageType.GlobalName}, {h.ResponseType!.GlobalName}>), static sp => sp.GetRequiredService<{h.HandlerType.GlobalName}>(), lt));");
        }
        // Notification handlers (multiple per type, AddEnumerable-style via raw Add)
        foreach (var h in notificationHandlers.SelectMany(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.INotificationHandler<{h.MessageType.GlobalName}>), typeof({h.HandlerType.GlobalName}), lt));");
        }
        // Pre-processors
        foreach (var h in preProcessors.SelectMany(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestPreProcessor<{h.MessageType.GlobalName}>), typeof({h.HandlerType.GlobalName}), lt));");
        }
        // Post-processors
        foreach (var h in postProcessors.SelectMany(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestPostProcessor<{h.MessageType.GlobalName}, {h.ResponseType!.GlobalName}>), typeof({h.HandlerType.GlobalName}), lt));");
        }
        // Exception handlers
        foreach (var h in exceptionHandlers.SelectMany(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestExceptionHandler<{h.MessageType.GlobalName}, {h.ResponseType!.GlobalName}, {h.ExceptionType!.GlobalName}>), typeof({h.HandlerType.GlobalName}), lt));");
        }
        // Exception actions
        foreach (var h in exceptionActions.SelectMany(kv => kv.Value))
        {
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IRequestExceptionAction<{h.MessageType.GlobalName}, {h.ExceptionType!.GlobalName}>), typeof({h.HandlerType.GlobalName}), lt));");
        }
        // Closed pipeline behaviors discovered by class scan. Registered under the
        // framework interface so the runtime enumeration fallback picks them up.
        foreach (var b in model.Behaviors)
        {
            if (b.IsOpenGeneric) continue;
            if (b.ClosedRequestType is null || b.ClosedResponseType is null) continue;
            var iface = b.Kind == BehaviorKind.Request
                ? $"global::MDator.IPipelineBehavior<{b.ClosedRequestType.GlobalName}, {b.ClosedResponseType.GlobalName}>"
                : $"global::MDator.IStreamPipelineBehavior<{b.ClosedRequestType.GlobalName}, {b.ClosedResponseType.GlobalName}>";
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({iface}), typeof({b.BehaviorType.GlobalName}), lt));");
        }

        // Open behaviors — self-register under their own open-generic type only.
        // The fused code path resolves them by implementation type. We intentionally
        // do NOT register them under IPipelineBehavior<,> because the generated
        // pipeline ALSO enumerates that interface for runtime-added behaviors; a
        // double registration would cause every fused behavior to execute twice.
        // Users who want a behavior in both paths can declare it via the attribute
        // (fused path) OR via services.AddTransient(typeof(IPipelineBehavior<,>), ...)
        // in configure (runtime path), but not both.
        foreach (var b in model.Behaviors)
        {
            if (!b.IsOpenGeneric) continue;
            w.Line($"services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({b.BehaviorType.GlobalNameUnbound}), typeof({b.BehaviorType.GlobalNameUnbound}), lt));");
            w.Line($"cfg.RegisterOpenBehavior(typeof({b.BehaviorType.GlobalNameUnbound}), {b.Order});");
        }

        w.CloseBrace();
        w.CloseBrace();
    }

    private static void EmitMediator(
        CodeWriter w,
        Dictionary<string, HandlerInfo> requestHandlers,
        Dictionary<string, HandlerInfo> voidHandlers,
        Dictionary<string, HandlerInfo> streamHandlers,
        Dictionary<string, List<HandlerInfo>> notificationHandlers,
        Dictionary<string, List<HandlerInfo>> preProcessors,
        Dictionary<(string, string), List<HandlerInfo>> postProcessors,
        Dictionary<(string, string), List<HandlerInfo>> exceptionHandlers,
        Dictionary<string, List<HandlerInfo>> exceptionActions,
        List<BehaviorInfo> openRequestBehaviors,
        List<BehaviorInfo> openStreamBehaviors)
    {
        w.Line("internal sealed class GeneratedMediator : global::MDator.IMediator");
        w.OpenBrace();
        w.Line("private readonly global::System.IServiceProvider _sp;");
        w.Line("private readonly global::MDator.MDatorConfiguration _cfg;");
        w.Line("private readonly global::MDator.INotificationPublisher _publisher;");
        w.Line();
        w.Line("public GeneratedMediator(global::System.IServiceProvider sp, global::MDator.MDatorConfiguration cfg, global::MDator.INotificationPublisher publisher)");
        w.OpenBrace();
        w.Line("_sp = sp;");
        w.Line("_cfg = cfg;");
        w.Line("_publisher = publisher;");
        w.CloseBrace();
        w.Line();

        EmitSendWithResponse(w, requestHandlers);
        EmitSendVoid(w, voidHandlers);
        EmitSendObject(w, requestHandlers, voidHandlers);
        EmitCreateStream(w, streamHandlers);
        EmitCreateStreamObject(w, streamHandlers);
        EmitPublish(w, notificationHandlers);
        EmitPublishObject(w, notificationHandlers);

        // Per-request pipeline composers
        foreach (var kv in requestHandlers)
        {
            EmitRequestPipeline(w, kv.Value, preProcessors, postProcessors,
                exceptionHandlers, exceptionActions, openRequestBehaviors);
        }
        foreach (var kv in voidHandlers)
        {
            EmitVoidRequestPipeline(w, kv.Value, preProcessors, openRequestBehaviors);
        }
        foreach (var kv in streamHandlers)
        {
            EmitStreamPipeline(w, kv.Value, openStreamBehaviors);
        }
        foreach (var kv in notificationHandlers)
        {
            EmitNotificationPublish(w, kv.Key, kv.Value);
        }

        w.CloseBrace();
    }

    private static void EmitSendWithResponse(CodeWriter w, Dictionary<string, HandlerInfo> requestHandlers)
    {
        w.Line("public global::System.Threading.Tasks.Task<TResponse> Send<TResponse>(global::MDator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        w.OpenBrace();
        w.Line("switch (request)");
        w.OpenBrace();
        foreach (var h in SortedByTypeHierarchy(requestHandlers.Values))
        {
            w.Line($"case {h.MessageType.GlobalName} __req_{h.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return (global::System.Threading.Tasks.Task<TResponse>)(object)SendCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken);");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return SendUnknown<TResponse>(request, cancellationToken);");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();

        w.Line("private global::System.Threading.Tasks.Task<TResponse> SendUnknown<TResponse>(global::MDator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken)");
        w.OpenBrace();
        w.Line("return global::MDator.RuntimeDispatch.SendFallback<TResponse>(_sp, _cfg, request, cancellationToken);");
        w.CloseBrace();
        w.Line();
    }

    private static void EmitSendVoid(CodeWriter w, Dictionary<string, HandlerInfo> voidHandlers)
    {
        w.Line("public global::System.Threading.Tasks.Task Send<TRequest>(TRequest request, global::System.Threading.CancellationToken cancellationToken = default) where TRequest : global::MDator.IRequest");
        w.OpenBrace();
        w.Line("switch (request)");
        w.OpenBrace();
        foreach (var h in SortedByTypeHierarchy(voidHandlers.Values))
        {
            w.Line($"case {h.MessageType.GlobalName} __req_{h.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return SendVoidCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken);");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return global::MDator.RuntimeDispatch.SendVoidFallback(_sp, _cfg, request, cancellationToken);");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitSendObject(
        CodeWriter w,
        Dictionary<string, HandlerInfo> requestHandlers,
        Dictionary<string, HandlerInfo> voidHandlers)
    {
        w.Line("public async global::System.Threading.Tasks.Task<object?> Send(object request, global::System.Threading.CancellationToken cancellationToken = default)");
        w.OpenBrace();
        w.Line("switch (request)");
        w.OpenBrace();
        foreach (var h in SortedByTypeHierarchy(requestHandlers.Values))
        {
            w.Line($"case {h.MessageType.GlobalName} __req_{h.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return await SendCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken).ConfigureAwait(false);");
            w.Dedent();
        }
        foreach (var h in SortedByTypeHierarchy(voidHandlers.Values))
        {
            w.Line($"case {h.MessageType.GlobalName} __req_{h.MessageType.Identifier}:");
            w.Indent();
            w.Line($"await SendVoidCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken).ConfigureAwait(false); return null;");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return await global::MDator.RuntimeDispatch.SendObjectFallback(_sp, _cfg, request, cancellationToken).ConfigureAwait(false);");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitCreateStream(CodeWriter w, Dictionary<string, HandlerInfo> streamHandlers)
    {
        w.Line("public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(global::MDator.IStreamRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        w.OpenBrace();
        w.Line("switch (request)");
        w.OpenBrace();
        foreach (var h in SortedByTypeHierarchy(streamHandlers.Values))
        {
            w.Line($"case {h.MessageType.GlobalName} __req_{h.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return (global::System.Collections.Generic.IAsyncEnumerable<TResponse>)(object)StreamCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken);");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return global::MDator.RuntimeDispatch.StreamFallback<TResponse>(_sp, _cfg, request, cancellationToken);");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitCreateStreamObject(CodeWriter w, Dictionary<string, HandlerInfo> streamHandlers)
    {
        // When there are no stream handlers at all in this assembly, delegate
        // entirely to the runtime fallback (which resolves cross-assembly handlers
        // from DI). No async/yield needed — just return the fallback enumerable.
        if (streamHandlers.Count == 0)
        {
            w.Line("public global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(object request, global::System.Threading.CancellationToken cancellationToken = default)");
            w.OpenBrace();
            w.Line("return global::MDator.RuntimeDispatch.StreamObjectFallback(_sp, _cfg, request, cancellationToken);");
            w.CloseBrace();
            w.Line();
            return;
        }

        w.Line("public async global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(object request, [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken = default)");
        w.OpenBrace();
        foreach (var h in SortedByTypeHierarchy(streamHandlers.Values))
        {
            w.Line($"if (request is {h.MessageType.GlobalName} __req_{h.MessageType.Identifier})");
            w.OpenBrace();
            w.Line($"await foreach (var __item in StreamCore_{h.MessageType.Identifier}(__req_{h.MessageType.Identifier}, cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))");
            w.OpenBrace();
            w.Line("yield return __item;");
            w.CloseBrace();
            w.Line("yield break;");
            w.CloseBrace();
        }
        // Fallback: resolve cross-assembly stream handlers from DI.
        w.Line("await foreach (var __item in global::MDator.RuntimeDispatch.StreamObjectFallback(_sp, _cfg, request, cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))");
        w.OpenBrace();
        w.Line("yield return __item;");
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitPublish(CodeWriter w, Dictionary<string, List<HandlerInfo>> notificationHandlers)
    {
        w.Line("public global::System.Threading.Tasks.Task Publish<TNotification>(TNotification notification, global::System.Threading.CancellationToken cancellationToken = default) where TNotification : global::MDator.INotification");
        w.OpenBrace();
        w.Line("switch (notification)");
        w.OpenBrace();
        foreach (HandlerInfo? first in notificationHandlers.Select(kv => kv.Value[0]))
        {
            w.Line($"case {first.MessageType.GlobalName} __n_{first.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return PublishCore_{first.MessageType.Identifier}(__n_{first.MessageType.Identifier}, cancellationToken);");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return global::System.Threading.Tasks.Task.CompletedTask;");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitPublishObject(CodeWriter w, Dictionary<string, List<HandlerInfo>> notificationHandlers)
    {
        w.Line("public global::System.Threading.Tasks.Task Publish(object notification, global::System.Threading.CancellationToken cancellationToken = default)");
        w.OpenBrace();
        w.Line("if (notification is null) throw new global::System.ArgumentNullException(nameof(notification));");
        w.Line("if (notification is not global::MDator.INotification) throw new global::System.ArgumentException(\"MDator: Publish requires an INotification instance.\", nameof(notification));");
        w.Line("switch (notification)");
        w.OpenBrace();
        foreach (HandlerInfo? first in notificationHandlers.Select(kv => kv.Value[0]))
        {
            w.Line($"case {first.MessageType.GlobalName} __n_{first.MessageType.Identifier}:");
            w.Indent();
            w.Line($"return PublishCore_{first.MessageType.Identifier}(__n_{first.MessageType.Identifier}, cancellationToken);");
            w.Dedent();
        }
        w.Line("default:");
        w.Indent();
        w.Line("return global::System.Threading.Tasks.Task.CompletedTask;");
        w.Dedent();
        w.CloseBrace();
        w.CloseBrace();
        w.Line();
    }

    private static void EmitRequestPipeline(
        CodeWriter w,
        HandlerInfo handler,
        Dictionary<string, List<HandlerInfo>> preProcessors,
        Dictionary<(string, string), List<HandlerInfo>> postProcessors,
        Dictionary<(string, string), List<HandlerInfo>> exceptionHandlers,
        Dictionary<string, List<HandlerInfo>> exceptionActions,
        List<BehaviorInfo> openRequestBehaviors)
    {
        var req = handler.MessageType;
        var resp = handler.ResponseType!;
        var reqT = req.GlobalName;
        var respT = resp.GlobalName;

        preProcessors.TryGetValue(reqT, out var pres);
        postProcessors.TryGetValue((reqT, respT), out var posts);
        exceptionHandlers.TryGetValue((reqT, respT), out var exHandlers);
        exceptionActions.TryGetValue(reqT, out var exActions);

        w.Line($"private async global::System.Threading.Tasks.Task<{respT}> SendCore_{req.Identifier}({reqT} request, global::System.Threading.CancellationToken ct)");
        w.OpenBrace();
        w.Line($"var handler = _sp.GetRequiredService<global::MDator.IRequestHandler<{reqT}, {respT}>>();");
        if (pres is { Count: > 0 })
            w.Line($"var __pre = _sp.GetServices<global::MDator.IRequestPreProcessor<{reqT}>>();");
        if (posts is { Count: > 0 })
            w.Line($"var __post = _sp.GetServices<global::MDator.IRequestPostProcessor<{reqT}, {respT}>>();");
        w.Line();

        // Core delegate (innermost): pre → handler → post.
        w.Line($"global::MDator.RequestHandlerDelegate<{respT}> next = async () =>");
        w.OpenBrace();
        if (pres is { Count: > 0 })
        {
            w.Line("foreach (var __p in __pre) await __p.Process(request, ct).ConfigureAwait(false);");
        }
        w.Line("var __resp = await handler.Handle(request, ct).ConfigureAwait(false);");
        if (posts is { Count: > 0 })
        {
            w.Line("foreach (var __p in __post) await __p.Process(request, __resp, ct).ConfigureAwait(false);");
        }
        w.Line("return __resp;");
        w.CloseBraceWithSemicolon();
        w.Line();

        // Fused open behaviors. We resolve each as its closed type, outermost last so
        // that when we invoke `next` at the end, the outermost is called first.
        // Resolve in reverse declared order so declared-earlier = outermost.
        if (openRequestBehaviors.Count > 0)
        {
            var i = 0;
            foreach (var b in ((IEnumerable<BehaviorInfo>)openRequestBehaviors).Reverse())
            {
                var bType = b.BehaviorType.GlobalNameWithoutGenerics;
                w.Line($"var __b_{i} = _sp.GetRequiredService<{bType}<{reqT}, {respT}>>();");
                w.Line("{ var __prev = next; next = () => __b_" + i + ".Handle(request, __prev, ct); }");
                i++;
            }
        }
        w.Line();

        // Runtime-added behaviors (skipped under FuseOnly). Open behaviors declared
        // via [assembly: OpenBehavior] are NOT registered under IPipelineBehavior<,>
        // (see RegistrationEmitter), so this enumeration only sees behaviors the
        // user registered explicitly at runtime — no dedupe needed.
        w.Line("if (!_cfg.FuseOnly)");
        w.OpenBrace();
        w.Line($"foreach (var __rb in _sp.GetServices<global::MDator.IPipelineBehavior<{reqT}, {respT}>>())");
        w.OpenBrace();
        w.Line("{ var __prev2 = next; next = () => __rb.Handle(request, __prev2, ct); }");
        w.CloseBrace();
        w.CloseBrace();
        w.Line();

        // Exception wrap.
        if (exHandlers is { Count: > 0 } || exActions is { Count: > 0 })
        {
            w.Line("try");
            w.OpenBrace();
            w.Line("return await next().ConfigureAwait(false);");
            w.CloseBrace();
            w.Line("catch (global::System.Exception __ex)");
            w.OpenBrace();
            w.Line($"var __state = new global::MDator.RequestExceptionHandlerState<{respT}>();");
            if (exHandlers is { Count: > 0 })
            {
                foreach (var h in exHandlers)
                {
                    var exT = h.ExceptionType!.GlobalName;
                    w.Line($"if (__ex is {exT} __ex_{h.ExceptionType.Identifier} && !__state.Handled)");
                    w.OpenBrace();
                    w.Line($"foreach (var __h in _sp.GetServices<global::MDator.IRequestExceptionHandler<{reqT}, {respT}, {exT}>>())");
                    w.OpenBrace();
                    w.Line($"await __h.Handle(request, __ex_{h.ExceptionType.Identifier}, __state, ct).ConfigureAwait(false);");
                    w.Line("if (__state.Handled) break;");
                    w.CloseBrace();
                    w.CloseBrace();
                }
            }
            if (exActions is { Count: > 0 })
            {
                foreach (var h in exActions)
                {
                    var exT = h.ExceptionType!.GlobalName;
                    w.Line($"if (__ex is {exT} __exa_{h.ExceptionType.Identifier})");
                    w.OpenBrace();
                    w.Line($"foreach (var __a in _sp.GetServices<global::MDator.IRequestExceptionAction<{reqT}, {exT}>>())");
                    w.OpenBrace();
                    w.Line($"await __a.Execute(request, __exa_{h.ExceptionType.Identifier}, ct).ConfigureAwait(false);");
                    w.CloseBrace();
                    w.CloseBrace();
                }
            }
            w.Line("if (__state.Handled) return __state.Response!;");
            w.Line("throw;");
            w.CloseBrace();
        }
        else
        {
            w.Line("return await next().ConfigureAwait(false);");
        }

        w.CloseBrace();
        w.Line();
    }

    private static void EmitVoidRequestPipeline(
        CodeWriter w,
        HandlerInfo handler,
        Dictionary<string, List<HandlerInfo>> preProcessors,
        List<BehaviorInfo> openRequestBehaviors)
    {
        var req = handler.MessageType;
        var reqT = req.GlobalName;
        preProcessors.TryGetValue(reqT, out var pres);

        // Void handlers are modeled as IRequestHandler<TRequest, Unit> internally so the
        // pipeline machinery is uniform. We synthesize a Unit-returning adapter so the
        // user's IRequestHandler<TRequest> can slot in.
        w.Line($"private async global::System.Threading.Tasks.Task SendVoidCore_{req.Identifier}({reqT} request, global::System.Threading.CancellationToken ct)");
        w.OpenBrace();
        w.Line($"var handler = _sp.GetRequiredService<global::MDator.IRequestHandler<{reqT}>>();");
        if (pres is { Count: > 0 })
            w.Line($"var __pre = _sp.GetServices<global::MDator.IRequestPreProcessor<{reqT}>>();");
        w.Line();

        w.Line("global::MDator.RequestHandlerDelegate<global::MDator.Unit> next = async () =>");
        w.OpenBrace();
        if (pres is { Count: > 0 })
            w.Line("foreach (var __p in __pre) await __p.Process(request, ct).ConfigureAwait(false);");
        w.Line("await handler.Handle(request, ct).ConfigureAwait(false);");
        w.Line("return global::MDator.Unit.Value;");
        w.CloseBraceWithSemicolon();
        w.Line();

        if (openRequestBehaviors.Count > 0)
        {
            var i = 0;
            foreach (var b in ((IEnumerable<BehaviorInfo>)openRequestBehaviors).Reverse())
            {
                var bType = b.BehaviorType.GlobalNameWithoutGenerics;
                w.Line($"var __b_{i} = _sp.GetRequiredService<{bType}<{reqT}, global::MDator.Unit>>();");
                w.Line("{ var __prev = next; next = () => __b_" + i + ".Handle(request, __prev, ct); }");
                i++;
            }
        }

        w.Line("if (!_cfg.FuseOnly)");
        w.OpenBrace();
        w.Line($"foreach (var __rb in _sp.GetServices<global::MDator.IPipelineBehavior<{reqT}, global::MDator.Unit>>())");
        w.OpenBrace();
        w.Line("{ var __prev2 = next; next = () => __rb.Handle(request, __prev2, ct); }");
        w.CloseBrace();
        w.CloseBrace();
        w.Line();

        w.Line("await next().ConfigureAwait(false);");
        w.CloseBrace();
        w.Line();
    }

    private static void EmitStreamPipeline(CodeWriter w, HandlerInfo handler, List<BehaviorInfo> openStreamBehaviors)
    {
        var req = handler.MessageType;
        var resp = handler.ResponseType!;
        var reqT = req.GlobalName;
        var respT = resp.GlobalName;

        w.Line($"private global::System.Collections.Generic.IAsyncEnumerable<{respT}> StreamCore_{req.Identifier}({reqT} request, global::System.Threading.CancellationToken ct)");
        w.OpenBrace();
        w.Line($"var handler = _sp.GetRequiredService<global::MDator.IStreamRequestHandler<{reqT}, {respT}>>();");
        w.Line($"global::MDator.StreamHandlerDelegate<{respT}> next = () => handler.Handle(request, ct);");

        if (openStreamBehaviors.Count > 0)
        {
            var i = 0;
            foreach (var b in ((IEnumerable<BehaviorInfo>)openStreamBehaviors).Reverse())
            {
                var bType = b.BehaviorType.GlobalNameWithoutGenerics;
                w.Line($"var __sb_{i} = _sp.GetRequiredService<{bType}<{reqT}, {respT}>>();");
                w.Line("{ var __prev = next; next = () => __sb_" + i + ".Handle(request, __prev, ct); }");
                i++;
            }
        }
        w.Line("if (!_cfg.FuseOnly)");
        w.OpenBrace();
        w.Line($"foreach (var __rb in _sp.GetServices<global::MDator.IStreamPipelineBehavior<{reqT}, {respT}>>())");
        w.OpenBrace();
        w.Line("{ var __prev2 = next; next = () => __rb.Handle(request, __prev2, ct); }");
        w.CloseBrace();
        w.CloseBrace();

        w.Line("return next();");
        w.CloseBrace();
        w.Line();
    }

    private static void EmitNotificationPublish(CodeWriter w, string _, List<HandlerInfo> handlers)
    {
        var first = handlers[0];
        var n = first.MessageType;
        var nT = n.GlobalName;

        w.Line($"private global::System.Threading.Tasks.Task PublishCore_{n.Identifier}({nT} notification, global::System.Threading.CancellationToken ct)");
        w.OpenBrace();
        w.Line($"var __all = _sp.GetServices<global::MDator.INotificationHandler<{nT}>>();");
        w.Line("var __list = new global::System.Collections.Generic.List<global::MDator.NotificationHandlerExecutor>();");
        w.Line("foreach (var __h in __all)");
        w.OpenBrace();
        w.Line($"var __hCapture = __h;");
        w.Line($"__list.Add(new global::MDator.NotificationHandlerExecutor(__hCapture, (__msg, __ct) => __hCapture.Handle(({nT})__msg, __ct)));");
        w.CloseBrace();
        w.Line("return _publisher.Publish(__list, notification, ct);");
        w.CloseBrace();
        w.Line();
    }
}
